### ISSUE TITLE
Add a method to test whether a DateTime matches a Schedule

### ISSUE THREAD

**Issue by zslayton** [zslayton/cron#16]
e.g.

```rust
let schedule = from_str("@weekly");
if schedule.includes(UTC.now()) {
  // ....
}
```

**Comment by koenichiwa** [comment]
Would this be sufficient?
```rust
pub fn contains<Z>(&self, date_time: DateTime<Z>) -> bool
    where
        Z: TimeZone,
    {
        self.fields.years.includes(date_time.year() as Ordinal)  &&
        self.fields.months.includes(date_time.month() as Ordinal) &&
        self.fields.days_of_week.includes(date_time.weekday().number_from_sunday()) &&
        self.fields.days_of_month.includes(date_time.day() as Ordinal) &&
        self.fields.hours.includes(date_time.hour() as Ordinal) &&
        self.fields.minutes.includes(date_time.minute() as Ordinal) &&
        self.fields.minutes.includes(date_time.second() as Ordinal)
    }
```

( I'm a bit unsure why it's TimeUnitSpec::includes instead of contains, the convention on collections seems to be `contains`, but I might be wrong. )

**Comment by zslayton** [comment]
I believe that's sufficient, yes. Accepting a `DateTime<_>` as a parameter rules out a lot of corner cases as the user will have already managed to create the value.

> ( I'm a bit unsure why it's TimeUnitSpec::includes instead of contains, the convention on collections seems to be contains, but I might be wrong. )

I think I used the name `includes` because a `Schedule` is not obviously a set or container. Conversationally, one might say of a lower-case 's' schedule:
* "Here's a datetime, is it on the schedule?" 
* "Is this datetime part of the schedule?"
* "Does the schedule include this datetime?"

To my ears, "does the schedule _contain_ this datetime?" feels a bit off. I'm not married to the name `includes`, though.

**Comment by koenichiwa** [comment]
Great, I'll write some tests to make sure

>I think I used the name includes because a Schedule is not obviously a set or container.

I get that. But 'years' and 'months' both obviously seem like a set of... years and months? I mean, `years.contains(year_x)` seemed so natural to me, that I was a bit surprised that it wouldn't compile

**Comment by zslayton** [comment]
Ah, I see what you mean. Sorry, I was focused on the method name in your code sample, but you were referring to `TimeUnitSpec`. My mistake.

In the case of `TimeUnitSpec`, I was trying to keep its implementation abstract. They're each implemented as a set, but from the user's perspective the question is "Does `1-6/2` include Tuesday?" rather than "Does the set of ordinals produced by parsing the expression `1-6/2` contain Tuesday?"

**Comment by koenichiwa** [comment]
I the user uses the function `years()` though, doesn't he expect something that works like a collection?
Don't get me wrong, I'm happy to keep it at `includes`, I'm just a bit suprised

Also, is `TimeUnitSpecEq` a good name for the tuple struct?
