### ISSUE TITLE
Parse step values (common extension that originated in BSD)

### ISSUE THREAD

**Issue by mehcode** [zslayton/cron#19]
https://www.freebsd.org/cgi/man.cgi?crontab%285%29

>   Step values can be	used in	conjunction with ranges.  Following a range
     with `/<number>`	specifies skips	of the number's	value through the
     range.  For example, `0-23/2` can be used in the	hours field to specify
     command execution every other hour	(the alternative in the	V7 standard is
     `0,2,4,6,8,10,12,14,16,18,20,22`).  Steps are also permitted after an
     asterisk, so if you want to say ``every two hours'', just use `*/2`.

**Comment by zslayton** [comment]
To clarify for others reading this issue: `cron` already supports periods in the form `start/step` (e.g. `0/2` for every two hours.) This feature is to track periods with ranges, allowing you to write `9-17/2` to convey "every other hour between 9am and 5pm." It will also add support for `*/2`, a shorthand equivalent to `0/2`.

**Comment by x1957** [comment]
> To clarify for others reading this issue: `cron` already supports periods in the form `start/step` (e.g. `0/2` for every two hours.) This feature is to track periods with ranges, allowing you to write `9-17/2` to convey "every other hour between 9am and 5pm." It will also add support for `*/2`, a shorthand equivalent to `0/2`.

so <code>*/5  *  *  *  *  *  *</code> now is invalid expression?

**Comment by zslayton** [comment]
This was added in PR #64.
