### ISSUE TITLE
Upgrade chrono to 0.4

### ISSUE THREAD

**Issue by lancecarlson** [zslayton/cron#25]
The dependency on 0.3 is causing dependency issues in my app. Can we get this upgraded? I know the implications of upgrading require a rename from UTC to Utc. Not sure of there are any changes required.

**Comment by zslayton** [comment]
I'm happy to update this, but I can't do it until the weekend at the earliest. PRs welcome if you have spare cycles!

**Comment by william20111** [comment]
I did a nasty search and replace in src, which replaced 4 mentions. Then same in tests which replaced quite a few. Ran the tests and they passed so might just be that easy..

```bash
%s/UTC/Utc/g
```

**Comment by william20111** [comment]
fired a PR in for this. https://github.com/zslayton/cron/pull/26

Will

**Comment by zslayton** [comment]
PR merged, thanks!

**Comment by zslayton** [comment]
Unsure why the CI didn't notice it, but a change to one of the unstable APIs is currently breaking the build. Will try to look at this tonight.
