### ISSUE TITLE
Unusable with new version of rust

### ISSUE THREAD

**Issue by TheUberCatman** [zslayton/cron#29]
The current version doesn't work with the current rust version

**Comment by william20111** [comment]
https://github.com/zslayton/cron/pull/27

Its fixed, just clone from github until its been updated in crates.io

**Comment by zslayton** [comment]
I need to publish a new version to crates.io. I'll try to do this ASAP.

**Comment by zslayton** [comment]
Version 0.4.0 is [available on crates.io](https://crates.io/crates/cron/0.4.0).
