### ISSUE TITLE
ScheduleIterator from `Schedule::after` sometimes skips the first event

### ISSUE THREAD

**Issue by tirr-c** [zslayton/cron#32]
```rust
extern crate cron;
extern crate chrono;

fn main() {
    use chrono::TimeZone;

    let schedule = "0 0/10 * * * * *".parse::<cron::Schedule>().unwrap();

    let dt = chrono::NaiveDate::from_ymd(2017, 10, 24).and_hms(0, 0, 59);
    let dt = chrono::Utc.from_utc_datetime(&dt);
    println!("{}", schedule.after(&dt).next().unwrap());

    let dt = chrono::NaiveDate::from_ymd(2017, 10, 24).and_hms(0, 1, 0);
    let dt = chrono::Utc.from_utc_datetime(&dt);
    println!("{}", schedule.after(&dt).next().unwrap());
}
```

Both line should print `2017-10-24 00:10:00 UTC`. But I got this:

```
2017-10-24 00:10:00 UTC
2017-10-24 00:20:00 UTC
```

**Comment by kgtkr** [comment]
Mee too

now:`2018-11-15 22:30:00`

`00 00 23 * * * *` → `2018-11-16 23:00:00`
`00 00 * * * * *` → `2018-11-15 23:00:00`

**Comment by zslayton** [comment]
Thanks, @kgtkr  and @tirr-c , for reporting this. I'm not going to have time to investigate this for a while, unfortunately. I would be happy to review a PR if either of you have the bandwidth to put one together.

**Comment by zslayton** [comment]
I've tracked down the source of the problem. I'll put out a bugfix when I get the chance. If anyone would like to work on it sooner, please comment here and I can post a detailed explanation.

**Comment by zslayton** [comment]
I've added your examples as unit tests. Please let me know if you have further issues.
