### ISSUE TITLE
Noob question: why nightly ? is it a permanent choice ?

### ISSUE THREAD

**Issue by jbruggem** [zslayton/cron#36]
Disclaimer: I'm rather new to rust's world. My question might come from a lack of knowledge of how things work.

I'm interested in using this lib is a small pet project. I have been using rust's `stable release` so far for that project, which means it will fail to compile `cron`, which requires some nightly (?) features.

Is this permanent, or does `cron` aim to support rust stable at some point ?

More generally, is the choice to use nightly features guided by some kind of recommendation ? Should I myself follow those ?

Thanks for your help !

**Comment by zslayton** [comment]
Hello!

> why nightly ?

I created `cron` for fun and wanted to take advantage of some unstable features. Specifically:

* [`RangeBounds`](https://doc.rust-lang.org/std/ops/trait.RangeBounds.html) ([stabilizing soon](https://github.com/rust-lang/rust/pull/51033))
* [`Iterator::step_by`](https://github.com/rust-lang/rust/issues/27741) ([stabilizing soon](https://github.com/rust-lang/rust/pull/51320))
* ~~`impl Trait`~~ ([now stable](https://github.com/rust-lang/rust/issues/34511))

> Is this permanent, or does cron aim to support rust stable at some point ?

I do not intend to add other unstable features to `cron`, so when these reach stable rust I can remove the nightly requirement. All of the remaining features have had their RFCs accepted and are being implemented, so it shouldn't be too much longer.

> More generally, is the choice to use nightly features guided by some kind of recommendation ? 

Building on stable should be the default choice for new crates. If there's a nightly feature you want to use that's just syntactic sugar for some existing Rust functionality, you might choose to avoid it for the sake of keeping your project on stable. However, some unstable features offer functionality that you can't achieve on stable. In that case, going with nightly would be your only option.

If the feature that you want to use is in a somewhat isolated part of your crate, you can allow users to opt into using it with [Cargo features](https://doc.rust-lang.org/cargo/reference/manifest.html#the-features-section). I've never used this feature myself.

**Comment by jbruggem** [comment]
Hi zslayton,

thanks for the awesome, thorough and interesting reply !

**Comment by zslayton** [comment]
Thanks to [a recent pull request](https://github.com/zslayton/cron/pull/39), the latest version of `cron` (v0.5.0) now builds on stable Rust (v1.28.0).
