### ISSUE TITLE
::from_str but no ::to_str

### ISSUE THREAD

**Issue by thundergolfer** [zslayton/cron#46]
Going from a cron string to a `Schedule` struct is nice and easy, but why can't you easily go from a `Schedule` back to its string representation?

**Comment by bittrance** [comment]
I'm missing this as well. Would you accept PRs for `impl Display for Schedule` and/or a `to_string()` methods?

**Comment by zslayton** [comment]
Sure, I'd be happy to accept a PR for this. Just to clarify the scope:

* We'd add a new `String` field to the `Schedule` struct that stores the original input text that was parsed
* Both `Display` and `to_string()` would use that text for their implementations.

Is that what you had in mind? 

I'd like to avoid trying to optimize the original text representation (for example: converting `1,2,3,4` to `1-4`) since that's a much bigger can of worms.

**Comment by bittrance** [comment]
A possible implementation can be found at bittrance/cron#1 . However, `Schedule` is a public struct which a user may construct manually, so we will only have "original" input if the schedule was created with the `FromStr` implementation. We don't have struct inheritance in Rust, so we can't trivially use different backing structs for `FromStr` and "raw" construction.

In this respect, having the various fields be able to recreate a string representation would better respect the current API.

Alternatively, you could expose `Schedule::from` as a constructor?

**Comment by zslayton** [comment]
> However, Schedule is a public struct which a user may construct manually

I don't believe this is the case. While the struct itself is public, [its member fields are not](https://github.com/zslayton/cron/blob/19591d69e5679f8d4696760a6a763ea05707601a/src/schedule.rs#L13-L21), which should preclude users from constructing new instances of it on their own. I've created [a minimal code example](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=43fb97299ba33a8a987f59fc6713e9f3) demonstrating this. Let me know if I've misunderstood something.

**Comment by bittrance** [comment]
Indeed, this is the aspect of Rust visibility system that I never manage to internalize. Very well, then. Here's the PR #54 .

**Comment by rtyler** [comment]
I believe with #54 merged this can be closed

**Comment by zslayton** [comment]
Addressed by #54.
