### ISSUE TITLE
0.6.1 release

### ISSUE THREAD

**Issue by Licenser** [zslayton/cron#53]
Heya @zslayton is there a chance to get a quick 0.6.1 release with the clone derive? :) pleeeaaaasseee?

**Comment by zslayton** [comment]
Hi, sorry for the delayed reply. I'll try to look into this over the weekend.

**Comment by Licenser** [comment]
Heya thank you so much! :D

**Comment by zslayton** [comment]
Hi @Licenser, I just published v0.6.1. 👍

**Comment by Licenser** [comment]
Thanks for the quick release:)
