### ISSUE TITLE
Schedule to implement debug

### ISSUE THREAD

**Issue by budde25** [zslayton/cron#58]
Hello,
First off great library, thanks for all the work you've done.

I am having an issue where I am trying to implement schedule as a custom parser for structopt/clap. Unfortunately it won't let me because schedule needs to implement debug in order to printed by the library. I'm kinda new to rust thought so if there is a good reason that it doesn't implement debug that totally fine.

**Comment by zslayton** [comment]
Hi!

> if there is a good reason that it doesn't implement debug that totally fine

It actually [_does_ implement `Debug`](https://github.com/zslayton/cron/blob/a3fcd4a7c23ddde15d7a88a28453a0d1f6602fd9/src/schedule.rs#L13), but I hadn't gotten around to cutting a new release with that change in Cargo. 😛 Thanks for opening an issue, I'll try to find some time to do that soon.

**Comment by budde25** [comment]
Awesome. that would be great since I was also trying to use the toString method (or whatever the equvalent is) and I saw that it got merged in the code a couple months ago but the crate was 4 months old. Thank you!

**Comment by zslayton** [comment]
This is included in [the new `v0.7.0` release](https://github.com/zslayton/cron/releases/tag/v0.7.0).
