### ISSUE TITLE
any plans to continue this crate?

### ISSUE THREAD

**Issue by ernestrc** [zslayton/cron#7]

**Comment by zslayton** [comment]
Yes. It's on the backburner for me at the moment as I'm working on an overdue revamp of my other projects. I'm hoping to write a real grammar and use one of the many parser generators that have sprung up recently on crates.io to flesh this out.

**Comment by ernestrc** [comment]
I need something like this http://www.quartz-scheduler.org/documentation in rust. I think I will wait for now until you or smbdy finishes a cron parser and then I will see If I can implement the scheduling part

**Comment by zslayton** [comment]
I'm now rewriting this crate using [`nom`](http://rust.unhandledexpression.com/nom/index.html). It will handle:
* Parsing cron expressions
* Testing whether a [`DateTime`](https://docs.rs/chrono/*/chrono/datetime/struct.DateTime.html) matches an expression
* Iterating over `DateTime`s that match an expression within a specified time window

For a crate that offers in-process scheduling, check out @mehcode's [schedule-rs](https://github.com/mehcode/schedule-rs) crate, a work in progress.
