### ISSUE TITLE
Split Schedule into source and a ScheduleFields struct. Also remove Option from Schedule::source

### ISSUE THREAD

**Issue by koenichiwa** [zslayton/cron#71]
It might be interesting to create a ScheduleFields struct like such:
```rust
pub struct ScheduleFields {
    years: Years,
    days_of_week: DaysOfWeek,
    months: Months,
    days_of_month: DaysOfMonth,
    hours: Hours,
    minutes: Minutes,
    seconds: Seconds,
}
```
And change the Schedule field to:
```rust
pub struct Schedule {
    source: String,
    fields: ScheduleFields
}
```

This means that you can change the FromStr implementation for Schedule to:
```rust
 fn from_str(expression: &str) -> Result<Self, Self::Err> {
    match schedule(Input(expression)) {
        Ok((_, schedule_fields)) => { 
            Ok(Schedule::new(
                String::from(expression), 
                schedule_fields)
            )
        },  // Extract from nom tuple
        Err(_) => Err(ErrorKind::Expression("Invalid cron expression.".to_owned()).into()), //TODO: Details
    }
}
```
And because of that, source doesn't need to be an Option anymore.

To prevent any breaking changes you can change the TimeSpec functions in Schedule to
```rust
pub fn years(&self) -> &impl TimeUnitSpec {
    &self.fields.years // NB: instead of &self.hours
}
// etc
```
Lastly If you expose ScheduleFields (and add a getter to Schedule), it can be used for equality. This means that you can use the Schedule::source for a quick equality check of Schedules, and if you have a use case where you need to check for equivalence, you can manually choose to use the more "expensive" ScheduleFields equality check. This might be useful for #61

**Comment by zslayton** [comment]
I'm in favor of this change. 👍 

> Lastly If you expose ScheduleFields (and add a getter to Schedule), it can be used for equality. This means that you can use the Schedule::source for a quick equality check of Schedules, and if you have a use case where you need to check for equivalence, you can manually choose to use the more "expensive" ScheduleFields equality check.

I'd like to offer this functionality, but rather than exposing `ScheduleFields` I'd have something like a `pub fn ordinals_eq(&self, other: Schedule) -> bool` method. This keeps the `ScheduleFields` type internal, allowing us to do other refactoring in the future if we need to. The `Schedule` type [already allows you to access the `TimeUnitSpec` of each field](https://github.com/zslayton/cron/blob/master/src/schedule.rs#L473-L513). Thoughts?

**Comment by koenichiwa** [comment]
A use case to expose the fields would be that you can use them as a key for a map. See: https://github.com/zslayton/cron/pull/62#issuecomment-768425420

**Comment by zslayton** [comment]
This may be a naming problem, but the distinction between a `Schedule` and a `ScheduleFields` isn't very useful to an end-user. The primary difference would be their definition of traits like `PartialEq`; there wouldn't be much reason for the user to request the `ScheduleFields` beyond that. They could achieve the same thing with [a wrapper type](https://doc.rust-lang.org/rust-by-example/generics/new_types.html), something like:

```rust
struct OrdinalsEqSchedule(Schedule);
//...impl PartialEq to use `ordinals_eq`

let my_schedule: Schedule = /*...*/;
let tasks: Vec<ExecuteOnSchedule> = /*...*/;
let mut tasks_to_execute: HashMap<OrdinalsEqSchedule, Vec<ExecuteOnSchedule>> = HashMap::new();
tasks_to_execute.insert(OrdinalsEqSchedule(my_schedule), tasks);
```

This makes me think that the comparatively expensive ordinals check should be `Schedule`'s go-to definition of equality and that someone concerned with performance would instead do `schedule1.expression() == schedule2.expression()` or use `schedule.expression()` as their map key.

**Comment by koenichiwa** [comment]
Checking only on the TimeSpecs checks for equivalence though, not complete equality. The less expensive check on only the string checks for complete equality of two Schedules. I can stand behind exposing a wrapper that checks equality on just the TimeSpecs, but I would keep Schedule's standard equality check as a check on just the string.
